qqGroup:
  - '111'
  - '1111'
  - '11'
  - '11'
user: '111111'
qqBot: 222
openWelcome: true #入群欢迎开关
welcome: "" #入群欢迎
menuMessage: "   小助手菜单\n可用的功能有：\n-1.2042战绩查询，前缀为#cx\n-2.2042武器数据图输出，前缀为#wp\n-3.2042载具数据图输出，前缀为#vh\n-4.2042专家数据图输出，前缀为#cl\n-5.数据绑定#bd id 平台，都为必填参数\n---对于除绑定外的指令结构都为type id 平台（不填默认为pc）
其中type为每个指令的前缀\n---对于绑定后的玩家只需要输入前缀即可，既#cx等等，绑定后机器人会自动填入你之前的值" #菜单选项
openRequestValidation: false #对于是否开启入群验证，入群自动验证
RequestIssue: ""#填写你的入群问题，负责无法正确验证
tempPlayer: 10 #临时玩家允许的数量，请不要设置太多
groupChatInterval: 180 #设置群聊查询间隔，当有人聊天时在多少秒后才可以查询数据。单位（秒）
preGet: false #该选项作用与查询前的准备，用于适应api抽风的情况，如果api无法正常获取并且id无法被搜索请打开此选项试试
PrivateChatSearch: false #是否允许私聊信息
cx: true
cl: true
vh: true
wp: true
kd: true
kill: true